AWSTemplateFormatVersion: '2010-09-09'
Description: CloudForce 004

Resources:
  CloudForceVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: CloudForceVPC
  MyKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: my-key-pair

  CloudForcePublic:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CloudForceVPC
      CidrBlock: 172.16.0.0/20
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: CloudForcePublic

  CloudForcePrivate:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CloudForceVPC
      CidrBlock: 172.16.128.0/20
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: CloudForcePrivate


  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CloudForceIG

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref CloudForceVPC
      InternetGatewayId: !Ref InternetGateway

  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref CloudForceVPC
      Tags:
        - Key: Name
          Value: PublicRouteTable

  PublicRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTablePublic
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  AssociatePublic1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref CloudForcePublic
      RouteTableId: !Ref RouteTablePublic

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02396cdd13e9a1257
      InstanceType: t2.micro
      subnetId: !Ref CloudForcePublic
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      KeyName: mykeypair
      UserData:
        #!/bin/bash
        yum update -y
        yum install -y httpd git
        systemctl start httpd
        systemctl enable httpd
        cd /var/www/html
        rm -rf *
        git clone https://github.com/lewisawe/cloudForceWebSawe.git .
        systemctl restart httpd
      Tags:
        - Key: Name
          Value: CloudForceEC2
      
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH and HTTP access via port 22 and
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: http
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0